-- ==================== 百宝箱农场 v1 ====================
-- 在 Supabase SQL Editor 执行这段 SQL

-- 1️⃣ 地块表（25块地）
CREATE TABLE farm_plots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plot_index smallint NOT NULL,
  crop text,
  planted_at timestamptz,
  status text DEFAULT 'empty' CHECK (status IN ('empty','growing','ready'))
);

ALTER TABLE farm_plots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "允许所有操作" ON farm_plots FOR ALL USING (true) WITH CHECK (true);

-- 2️⃣ 仓库表
CREATE TABLE farm_inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  crop text NOT NULL UNIQUE,
  count integer DEFAULT 0
);

ALTER TABLE farm_inventory ENABLE ROW LEVEL SECURITY;
CREATE POLICY "允许所有操作" ON farm_inventory FOR ALL USING (true) WITH CHECK (true);

-- 3️⃣ 初始化25块空地
INSERT INTO farm_plots (plot_index, status)
SELECT generate_series(0, 24), 'empty';

-- 4️⃣ 初始化种子库存（新手大礼包）
INSERT INTO farm_inventory (crop, count) VALUES
('carrot', 5),
('cabbage', 3),
('tomato', 2),
('strawberry', 0),
('herb', 0);
