import re

with open('D:\\openclaw-home\\.openclaw\\workspace\\xiabaibao\\index.html', 'r', encoding='utf-8') as f:
    content = f.read()

# ShowCdDetail replacement
old_cd = "function showCdDetail(id) {\n  const idx = findCdIdx(id);\n  if (idx === -1) { renderCountdowns(); return; }\n  const item = _cache.countdowns[idx];\n  const days = getCdDays(item);\n  const label = getCdLabel(days);\n  let html = `<button class=\"back-btn\" onclick=\"renderCountdowns()\">← 返回</button>`;\n  html += `<div class=\"card\">\n    <h3>${item.done ? '✅ ' : ''}${esc(item.title)}</h3>\n    <div class=\"meta\" style=\"margin:6px 0\">\n      📅 ${item.target_date} ${item.target_time || ''}\n      ${(item.tags||[]).length ? item.tags.map(t => '<span class=\"tag\">#' + esc(t) + '</span>').join('') : ''}\n    </div>`;\n  if (!item.done) {\n    html += `<div style=\"text-align:center;padding:16px 0\">\n      <span style=\"font-size:36px;font-weight:700;color:${label.color}\">${days < 0 ? '逾期' + Math.abs(days) + '天' : days + '天'}</span><br>\n      <span style=\"font-size:14px;color:#999\">${label.text}</span>\n    </div>`;\n  } else {\n    html += `<div style=\"text-align:center;padding:16px 0;color:#4caf50;font-size:18px\">🎉 已完成！</div>`;\n  }\n  if (item.description) html += `<p style=\"font-size:14px;color:#666;white-space:pre-wrap\">${esc(item.description)}</p>`;\n  html += `</div>`;\n  if (!item.done) {\n    html += `<button class=\"checkin-btn pending\" onclick=\"doCdDone(${item.id})\" style=\"margin:8px 0\">✅ 标记为已完成</button>`;\n  } else {\n    html += `<button class=\"checkin-btn done\" onclick=\"doCdUndo(${item.id})\" style=\"margin:8px 0\">↩️ 撤销完成</button>`;\n  }\n  html += `<button class=\"btn btn-danger btn-sm\" onclick=\"if(confirm('删除此倒计时？')){ deleteCd(${item.id}) }\" style=\"width:100%\">🗑️ 删除</button>`;\n  document.getElementById('countdownList').innerHTML = html;\n}"

new_cd = "function showCdDetail(id) {\n  const idx = findCdIdx(id);\n  if (idx === -1) { renderCountdowns(); return; }\n  const item = _cache.countdowns[idx];\n  const days = getCdDays(item);\n  const label = getCdLabel(days);\n  let html = `<div class=\"card detail-card\">\n      <div class=\"detail-header\">\n        <button class=\"detail-back\" onclick=\"renderCountdowns()\">← 返回</button>\n        <button class=\"detail-delete\" onclick=\"if(confirm('删除此倒计时？')){ deleteCd(${item.id}) }\">🗑️ 删除</button>\n      </div>\n      <div class=\"detail-title\" contenteditable=\"true\" onblur=\"updateCdField(${item.id},'title',this.innerText)\">${item.done ? '✅ ' : ''}${esc(item.title)}</div>\n      <div class=\"detail-meta\" style=\"margin-bottom:10px\">\n        📅 ${item.target_date} ${item.target_time || ''}\n        ${(item.tags||[]).length ? item.tags.map(t => '<span class=\"tag\">#' + esc(t) + '</span>').join('') : ''}\n      </div>`;\n  if (!item.done) {\n    html += `<div style=\"text-align:center;padding:16px 0\">\n      <span style=\"font-size:36px;font-weight:700;color:${label.color}\">${days < 0 ? '逾期' + Math.abs(days) + '天' : days + '天'}</span><br>\n      <span style=\"font-size:14px;color:#999\">${label.text}</span>\n    </div>`;\n  } else {\n    html += `<div style=\"text-align:center;padding:16px 0;color:#4caf50;font-size:18px\">🎉 已完成！</div>`;\n  }\n  if (item.description !== undefined) {\n    html += `<div class=\"detail-content\" contenteditable=\"true\" onblur=\"updateCdField(${item.id},'description',this.innerText)\">${esc(item.description||'')}</div>`;\n  }\n  html += `</div>`;\n  if (!item.done) {\n    html += `<button class=\"checkin-btn pending\" onclick=\"doCdDone(${item.id})\" style=\"margin:8px 0\">✅ 标记为已完成</button>`;\n  } else {\n    html += `<button class=\"checkin-btn done\" onclick=\"doCdUndo(${item.id})\" style=\"margin:8px 0\">↩️ 撤销完成</button>`;\n  }\n  document.getElementById('countdownList').innerHTML = html;\n}\n\nasync function updateCdField(id, field, value) {\n  const idx = findCdIdx(id);\n  if (idx === -1) return;\n  const update = {};\n  update[field] = value.trim();\n  if (update[field] === _cache.countdowns[idx][field]) return;\n  await sb.from('countdowns').update(update).eq('id', id);\n  _cache.countdowns[idx][field] = update[field];\n}"

if old_cd in content:
    content = content.replace(old_cd, new_cd)
    with open('D:\\openclaw-home\\.openclaw\\workspace\\xiabaibao\\index.html', 'w', encoding='utf-8') as f:
        f.write(content)
    print('SUCCESS: showCdDetail updated')
else:
    print('ERROR: showCdDetail old text not found')
    # Debug: find what's around that area
    idx = content.find('function showCdDetail')
    if idx >= 0:
        print(f'Found at position {idx}')
        print(repr(content[idx:idx+200]))
